name: Update RSS Feed

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  update-rss:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Download RSS feed
      run: |
        curl -o toutes_actualites.rss https://gouvernement.lu/fr/actualites/toutes_actualites.rss
    
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add toutes_actualites.rss
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update RSS feed" && git push)
